<a href="https://colab.research.google.com/github/Tuanyatuanya/MSSP607/blob/main/Participation_Week_08_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

In [2]:
!git clone https://github.com/tuanyatuanya/MSSP607.git

Cloning into 'MSSP607'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 139 (delta 70), reused 31 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (139/139), 1.03 MiB | 9.90 MiB/s, done.
Resolving deltas: 100% (70/70), done.

In [8]:
df = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week_7 folder/InternetSales.csv', encoding='latin-1')
display(df.head())

/tmp/ipython-input-332926898.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week_7 folder/InternetSales.csv', encoding='latin-1')

,ID,CustomerKey,GeographyKey,City,CountryRegionCode,EnglishCountryRegionName,CustomerAlternateKey,Title,FirstName,MiddleName,...,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,CarrierTrackingNumber,CustomerPONumber,OrderDate,DueDate,ShipDate
0,0,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,1912.1544,1912.1544,3399.99,271.9992,84.9998,NaN,NaN,1/19/2011,1/31/2011,1/26/2011
1,1,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,1265.6195,1265.6195,2319.99,185.5992,57.9998,NaN,NaN,1/18/2013,1/30/2013,1/25/2013
2,2,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,8.2205,8.2205,21.98,1.7584,0.5495,NaN,NaN,1/18/2013,1/30/2013,1/25/2013
3,3,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,1481.9379,1481.9379,2384.07,190.7256,59.6018,NaN,NaN,5/3/2013,5/15/2013,5/10/2013
4,4,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,10.8423,10.8423,28.99,2.3192,0.7248,NaN,NaN,5/3/2013,5/15/2013,5/10/2013

In [9]:
display(df.head())
display(df.info())
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

,ID,CustomerKey,GeographyKey,City,CountryRegionCode,EnglishCountryRegionName,CustomerAlternateKey,Title,FirstName,MiddleName,...,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,CarrierTrackingNumber,CustomerPONumber,OrderDate,DueDate,ShipDate
0,0,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,1912.1544,1912.1544,3399.99,271.9992,84.9998,NaN,NaN,1/19/2011,1/31/2011,1/26/2011
1,1,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,1265.6195,1265.6195,2319.99,185.5992,57.9998,NaN,NaN,1/18/2013,1/30/2013,1/25/2013
2,2,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,8.2205,8.2205,21.98,1.7584,0.5495,NaN,NaN,1/18/2013,1/30/2013,1/25/2013
3,3,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,1481.9379,1481.9379,2384.07,190.7256,59.6018,NaN,NaN,5/3/2013,5/15/2013,5/10/2013
4,4,11000,26,Rockhampton,AU,Australia,AW00011000,NaN,Jon,V,...,10.8423,10.8423,28.99,2.3192,0.7248,NaN,NaN,5/3/2013,5/15/2013,5/10/2013

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 60 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        60398 non-null  int64
 1   CustomerKey               60398 non-null  int64
 2   GeographyKey              60398 non-null  int64
 3   City                      60398 non-null  object
 4   CountryRegionCode         60398 non-null  object
 5   EnglishCountryRegionName  60398 non-null  object
 6   CustomerAlternateKey      60398 non-null  object
 7   Title                     307 non-null    object
 8   FirstName                 60398 non-null  object
 9   MiddleName                34903 non-null  object
 10  LastName                  60398 non-null  object
 11  NameStyle                 60398 non-null  bool
 12  BirthDate                 60398 non-null  object
 13  MaritalStatus             60398 non-null  object
 14  Suffix                    6 non-null      object
 15  Gender                    60398 non-null  object
 16  EmailAddress              60398 non-null  object
 17  YearlyIncome              60398 non-null  int64
 18  TotalChildren             60398 non-null  int64
 19  NumberChildrenAtHome      60398 non-null  int64
 20  EnglishEducation          60398 non-null  object
 21  SpanishEducation          60398 non-null  object
 22  FrenchEducation           60398 non-null  object
 23  EnglishOccupation         60398 non-null  object
 24  SpanishOccupation         60398 non-null  object
 25  FrenchOccupation          60398 non-null  object
 26  HouseOwnerFlag            60398 non-null  int64
 27  NumberCarsOwned           60398 non-null  int64
 28  AddressLine1              60398 non-null  object
 29  AddressLine2              1105 non-null   object
 30  Phone                     60398 non-null  object
 31  DateFirstPurchase         60398 non-null  object
 32  CommuteDistance           60398 non-null  object
 33  ProductKey                60398 non-null  int64
 34  EnglishProductName        60398 non-null  object
 35  OrderDateKey              60398 non-null  int64
 36  DueDateKey                60398 non-null  int64
 37  ShipDateKey               60398 non-null  int64
 38  CustomerKey.1             60398 non-null  int64
 39  PromotionKey              60398 non-null  int64
 40  CurrencyKey               60398 non-null  int64
 41  SalesTerritoryKey         60398 non-null  int64
 42  SalesOrderNumber          60398 non-null  object
 43  SalesOrderLineNumber      60398 non-null  int64
 44  RevisionNumber            60398 non-null  int64
 45  OrderQuantity             60398 non-null  int64
 46  UnitPrice                 60398 non-null  float64
 47  ExtendedAmount            60398 non-null  float64
 48  UnitPriceDiscountPct      60398 non-null  int64
 49  DiscountAmount            60398 non-null  int64
 50  ProductStandardCost       60398 non-null  float64
 51  TotalProductCost          60398 non-null  float64
 52  SalesAmount               60398 non-null  float64
 53  TaxAmt                    60398 non-null  float64
 54  Freight                   60398 non-null  float64
 55  CarrierTrackingNumber     0 non-null      float64
 56  CustomerPONumber          0 non-null      float64
 57  OrderDate                 60398 non-null  object
 58  DueDate                   60398 non-null  object
 59  ShipDate                  60398 non-null  object
dtypes: bool(1), float64(9), int64(21), object(29)
memory usage: 27.2+ MB

None

In [10]:
df['year'] = df['OrderDate'].dt.year
df['month'] = df['OrderDate'].dt.month
df['day_of_week'] = df['OrderDate'].dt.dayofweek
display(df[['OrderDate', 'year', 'month', 'day_of_week']].head())

   OrderDate  year  month  day_of_week
0 2011-01-19  2011      1            2
1 2013-01-18  2013      1            4
2 2013-01-18  2013      1            4
3 2013-05-03  2013      5            4
4 2013-05-03  2013      5            4

In [11]:
sales_ts = df.groupby('OrderDate')['SalesAmount'].sum().reset_index()
sales_ts = sales_ts.sort_values(by='OrderDate')
display(sales_ts.head())

   OrderDate  SalesAmount
0 2010-12-29   14477.3382
1 2010-12-30   13931.5200
2 2010-12-31   15012.1782
3 2011-01-01    7156.5400
4 2011-01-02   15012.1782

In [12]:
from prophet import Prophet

sales_ts = sales_ts.rename(columns={'OrderDate': 'ds', 'SalesAmount': 'y'})

model = Prophet()
model.fit(sales_ts)

INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjbvhp3uy/xdxeajny.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjbvhp3uy/q7_az64b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69363', 'data', 'file=/tmp/tmpjbvhp3uy/xdxeajny.json', 'init=/tmp/tmpjbvhp3uy/q7_az64b.json', 'output', 'file=/tmp/tmpjbvhp3uy/prophet_modelk782ggiv/prophet_model-20251027032646.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
03:26:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
03:26:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

In [17]:
future = model.make_future_dataframe(periods=5*365, freq='D')
forecast = model.predict(future)
display(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail())

             ds         yhat     yhat_lower     yhat_upper
2944 2019-01-23  -715.181842 -144371.159866  154324.303912
2945 2019-01-24  -565.006045 -146528.794993  154928.204385
2946 2019-01-25   162.204471 -141089.228485  154105.294029
2947 2019-01-26   611.765847 -142085.540637  158721.808584
2948 2019-01-27  1142.017824 -144178.818902  154775.929350

In [16]:
product_sales = df.groupby('EnglishProductName')['SalesAmount'].sum()
most_selling_product = product_sales.idxmax()
max_sales_amount = product_sales.max()

print(f"The product that generated the most sales is '{most_selling_product}' with a total sales amount of ${max_sales_amount:,.2f}")

The product that generated the most sales is 'Mountain-200 Black, 46' with a total sales amount of $1,373,469.55