In [3]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week_6 folder/Student Performance Data.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [13]:
transform_df = lambda dataframe: dataframe[['math score', 'reading score', 'writing score', 'total score']]

df_transformed = transform_df(df)
display(df_transformed.head())

   math score  reading score  writing score  total score
0          72             72             74          218
1          69             90             88          247
2          90             95             93          278
3          47             57             44          148
4          76             78             75          229