In [2]:
!git clone https://github.com/tuanyatuanya/MSSP607.git

fatal: destination path 'MSSP607' already exists and is not an empty directory.

In [3]:
import pandas as pd
import os

In [5]:
Apple = pd.read_csv('/content/MSSP607/Data/aapl.csv')
Facebook = pd.read_csv('/content/MSSP607/Data/fb.csv')
Amazon = pd.read_csv('/content/MSSP607/Data/amzn.csv')
Google = pd.read_csv('/content/MSSP607/Data/goog.csv')
Netflix = pd.read_csv('/content/MSSP607/Data/nflx.csv')

In [6]:
Apple['ticker'] = 'AAPL'
Facebook['ticker'] = 'FB'
Amazon['ticker'] = 'AMZN'
Google['ticker'] = 'GOOG'
Netflix['ticker'] = 'NFLX'

In [8]:
all_stocks = pd.concat([Apple, Facebook, Amazon, Google, Netflix], ignore_index=True)
all_stocks.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [9]:
all_stocks.to_csv('/content/MSSP607/Data/faanf.csv', index=False)

Combined data saved as 'faanf.csv' successfully!

In [11]:
top7_volume = all_stocks.nlargest(7, 'volume')
top7_volume

           date      open      high       low     close     volume ticker
393  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
304  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
308  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
305  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245  2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212  2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [13]:
melted_stocks = all_stocks.melt(
    id_vars=['date', 'ticker'],
    var_name='variable',
    value_name='value'
)

melted_stocks.head()

         date ticker variable     value
0  2018-01-02   AAPL     open  166.9271
1  2018-01-03   AAPL     open  169.2521
2  2018-01-04   AAPL     open  169.2619
3  2018-01-05   AAPL     open  170.1448
4  2018-01-08   AAPL     open  171.0375