In [1]:
import pandas as pd
import numpy as np
import re
df = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week_4 folder/parsed.csv')
print(df.head())

  alert  cdi      code                                             detail  \
0   NaN  NaN  37389218  https://earthquake.usgs.gov/fdsnws/event/1/que...
1   NaN  NaN  37389202  https://earthquake.usgs.gov/fdsnws/event/1/que...
2   NaN  4.4  37389194  https://earthquake.usgs.gov/fdsnws/event/1/que...
3   NaN  NaN  37389186  https://earthquake.usgs.gov/fdsnws/event/1/que...
4   NaN  NaN  73096941  https://earthquake.usgs.gov/fdsnws/event/1/que...

       dmin  felt    gap           ids   mag magType  ...     status  \
0  0.008693   NaN   85.0  ,ci37389218,  1.35      ml  ...  automatic
1  0.020030   NaN   79.0  ,ci37389202,  1.29      ml  ...  automatic
2  0.021370  28.0   21.0  ,ci37389194,  3.42      ml  ...  automatic
3  0.026180   NaN   39.0  ,ci37389186,  0.44      ml  ...  automatic
4  0.077990   NaN  192.0  ,nc73096941,  2.16      md  ...  automatic

            time                          title tsunami        type  \
0  1539475168010  M 1.4 - 9km NE of Aguanga, CA       0  earthquake
1  1539475129610  M 1.3 - 9km NE of Aguanga, CA       0  earthquake
2  1539475062610  M 3.4 - 8km NE of Aguanga, CA       0  earthquake
3  1539474978070  M 0.4 - 9km NE of Aguanga, CA       0  earthquake
4  1539474716050  M 2.2 - 10km NW of Avenal, CA       0  earthquake

                                               types     tz        updated  \
0         ,geoserve,nearby-cities,origin,phase-data, -480.0  1539475395144
1         ,geoserve,nearby-cities,origin,phase-data, -480.0  1539475253925
2  ,dyfi,focal-mechanism,geoserve,nearby-cities,o... -480.0  1539536756176
3         ,geoserve,nearby-cities,origin,phase-data, -480.0  1539475196167
4  ,geoserve,nearby-cities,origin,phase-data,scit... -480.0  1539477547926

                                                 url parsed_place
0  https://earthquake.usgs.gov/earthquakes/eventp...   California
1  https://earthquake.usgs.gov/earthquakes/eventp...   California
2  https://earthquake.usgs.gov/earthquakes/eventp...   California
3  https://earthquake.usgs.gov/earthquakes/eventp...   California
4  https://earthquake.usgs.gov/earthquakes/eventp...   California

[5 rows x 27 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
# Question a
df[
    (df.type == 'earthquake') | (df.parsed_place == 'Japan') | (df.magType == 'mb')
].describe(percentiles=[0.95])

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,325.000000,5983.000000,325.000000,6005.000000,9080.000000,93.000000,5205.000000,9081.000000,9081.000000,9.081000e+03,9081.000000,9080.000000,9.081000e+03
mean,2.755077,0.554447,12.440000,121.049810,1.501162,3.651398,19.212296,0.362219,57.613589,1.538284e+12,0.006717,-450.759912,1.538536e+12
std,1.015625,2.241892,49.241847,73.041716,1.217668,1.790523,15.608823,0.319442,92.984596,6.102902e+08,0.081688,234.736767,6.561813e+08
min,0.000000,0.000648,0.000000,12.000000,-1.260000,0.000000,0.000000,0.000000,0.000000,1.537229e+12,0.000000,-720.000000,1.537230e+12
50%,2.700000,0.057740,2.000000,105.000000,1.300000,3.720000,15.000000,0.210000,26.000000,1.538244e+12,0.000000,-480.000000,1.538621e+12
95%,4.300000,2.714900,40.600000,276.000000,4.400000,6.380000,49.000000,0.960000,298.000000,1.539321e+12,0.000000,120.000000,1.539400e+12
max,8.400000,53.737000,580.000000,355.910000,7.500000,9.120000,172.000000,1.910000,2015.000000,1.539475e+12,1.000000,720.000000,1.539537e+12

In [8]:
# Question b
indonesia_quakes = df[df["parsed_place"].str.contains("Indonesia", case=False, na=False)]
tsunami_percentage = (indonesia_quakes['tsunami'] == 1).mean() * 100
print(f"Percentage of earthquakes in Indonesia with tsunamis: {tsunami_percentage:.2f}%")

Percentage of earthquakes in Indonesia with tsunamis: 23.13%

In [14]:
#Question c
df[df.parsed_place == 'Nevada'].describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [19]:
#Question d
ring_of_fire_locations = [
    'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica', 'Guatemala', 'Mexico',
    'Japan', 'Philippines', 'Indonesia', 'New Zealand', 'Antarctica', 'Canada',
    'Fiji', 'Alaska', 'Washington', 'California', 'Russia', 'Taiwan', 'Tonga',
    'Kermadec Islands'
]
pattern = '|'.join([re.escape(location) for location in ring_of_fire_locations])

df['ring_of_fire'] = df['parsed_place'].str.contains(pattern, case=False, na=False)

df.loc[df['parsed_place'].str.contains('New Mexico', case=False, na=False), 'ring_of_fire'] = False

print(df[['parsed_place', 'ring_of_fire']].head())

  parsed_place  ring_of_fire
0   California          True
1   California          True
2   California          True
3   California          True
4   California          True

In [21]:
# Question e
ring_of_fire_counts = df['ring_of_fire'].value_counts()

print("Number of earthquakes in and outside the Ring of Fire:")
print(ring_of_fire_counts)

Number of earthquakes in and outside the Ring of Fire:
ring_of_fire
True     7184
False    2148
Name: count, dtype: int64

In [23]:
# Question f
ring_of_fire_tsunamis = df[(df['ring_of_fire'] == True) & (df['tsunami'] == 1)]
tsunami_count_ring_of_fire = len(ring_of_fire_tsunamis)
print(f"Number of tsunamis in the Ring of Fire: {tsunami_count_ring_of_fire}")

Number of tsunamis in the Ring of Fire: 45